Description of demo_foe
Home > unit > demo_foe.m
demo_foe
PURPOSE
Running this demos LS estimation of Output-Error model from frequency
SYNOPSIS
This is a script file.
DESCRIPTION
  Running this demos LS estimation of Output-Error model from frequency
  domain data
CROSS-REFERENCE INFORMATION
This function calls:
est EST: Computes an estimate of either a Box-Jenkins model or a state space
showbode SHOWBODE: This routine takes the results of an identification experiment
startZ This function accepts a data structure and tries to interpret what type
This function is called by:
demo_unit
SOURCE CODE
%  Running this demos LS estimation of Output-Error model from frequency
%  domain data
clear; close all;
global dm; if isempty(dm), clear global dm; dm=0; end
global dsp; if isempty(dsp), clear global dsp; dsp=1; end
global trans;
if dsp>1, clc; echo on; end
OPT.dsp = dsp;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Specify Experiment Conditions
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fs  = 1;      % Sampling Frequency in Hz
N   = 1000;   % Number of sammples
var = 1e-4;   % White measurement noise variance
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Specify True System
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
den     = real(poly([-0.1,-0.2,-0.02+j*1,-0.02-j*1,-0.01-j*0.1,-0.01+j*0.1]));
num     = 10*den(length(den));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Simulate a data record
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
w     = logspace(-3,log10(pi*fs),N);
F     = polyval(num,j*w)./polyval(den,j*w);
noise = sqrt(var)*(randn(size(F(:))) + j*randn(size(F(:))));
F     = F(:) + noise(:);
Z     = [F(:),w(:)];
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Specify Model Structure
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Ms.A    = length(den)-1;
Ms.B    = length(num);
Ms.op   = 's';
Ms.T    = 1/fs;
Ms.w    = w;
Ms.type = 'oe';
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Estimate on basis of noise corrupted data
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Gs = est(Z,Ms,OPT);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Plot the results
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if dsp,
    Gt.A    = den;
    Gt.B    = num;
    Gt.type = 'oe';
    Gt.op   = 's';
    Gt.T    = 1/fs;
    Gt.w    = w(:);
    Gt.disp.colour='b';
    Gt.disp.legend = 'True Response';
    Z = startZ(Z);
    Z.disp.legend = 'Measured Response';
    showbode(Gt,Gs,Z);
end
echo off;
if dm
 disp('  ')
 disp('---------------------------------------------------------------------')
 disp('  ')
 disp('You now have access to the MATLAB workspace so that you may examine')
 disp('the results of this simulation.  To return to the demos, type "dbcont"')
 disp(' ')
 keyboard;
end;