Description of demo_arx
Home > unit > demo_arx.m
demo_arx
PURPOSE
Running this demos estimation of ARX model structure
SYNOPSIS
This is a script file.
DESCRIPTION
  Running this demos estimation of ARX model structure
  using prediction error method
CROSS-REFERENCE INFORMATION
This function calls:
est EST: Computes an estimate of either a Box-Jenkins model or a state space
showbode SHOWBODE: This routine takes the results of an identification experiment
This function is called by:
demo_unit
SOURCE CODE
%  Running this demos estimation of ARX model structure
%  using prediction error method
clear; close all;
global dm; if isempty(dm), clear global dm; dm=0; end
global dsp; if isempty(dsp), clear global dsp; dsp=1; end
global trans;
if dsp>1, clc; echo on; end
OPT.dsp = dsp;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Specify Experiment Conditions
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
T   = 1;    % Sampling period in seconds
N   = 100;  % Number of Samples
var = 1e-1; % Measurement Noise Variance
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Specify true system
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
den     = real(poly([-0.1,-1,-0.2]));
num     = den(length(den));
[bq,aq] = c2dm(1,den,T,'zoh'); %introduces delay
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Simulate a data record
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Z.u     = randn(1,N);
noise   = sqrt(var)*randn(size(Z.u));
noise   = filter(1,aq,noise);
Z.y     = filter(bq,aq,Z.u)+noise;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Specify Model Structures
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Mq.A     = length(aq)-1;
Mq.B     = length(bq)-2; %delay is catered for elsewhere
Mq.T     = T;
Mq.type  = 'arx';
Mq.delay = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Estimate on basis of noise corrupted data
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Gq = est(Z,Mq,OPT);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Plot the results
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if dsp,
    Gt.A = aq;
    Gt.B = bq;
 Gt.w = Gq.w;
    Gt.type   = 'arx';
    Gt.colour = 'b';
    Gt.disp.legend = 'True Response';
    showbode(Gt,Gq);
end
echo off;
if dm
 disp('  ')
 disp('---------------------------------------------------------------------')
 disp('  ')
 disp('You now have access to the MATLAB workspace so that you may examine')
 disp('the results of this simulation.  To return to the demos, type "dbcont"')
 disp(' ')
 keyboard;
end;