Description of demo_fir
Home > unit > demo_fir.m
demo_fir
PURPOSE
Running this demos least squares estimation
SYNOPSIS
This is a script file.
DESCRIPTION
  Running this demos least squares estimation
  of FIR model structure
CROSS-REFERENCE INFORMATION
This function calls:
est EST: Computes an estimate of either a Box-Jenkins model or a state space
showbode SHOWBODE: This routine takes the results of an identification experiment
startM STARTM - function to initialise a model structure in case user has been
This function is called by:
demo_unit
SOURCE CODE
%  Running this demos least squares estimation
%  of FIR model structure
clear; close all;
global dm; if isempty(dm), clear global dm; dm=0; end
global dsp; if isempty(dsp), clear global dsp; dsp=1; end
global trans;
if dsp>1, clc; echo on; end
OPT.dsp = dsp;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Specify Experiment Conditions
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
T   = 0.1;    % Sampling period in seconds
var = 1e-4;   % Measurement noise variance
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Specify true system - ZOH impulse fresponse of cts defined system
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
bq = impulse(c2d(tf(1,real(poly([-1 -3+j -3-j]))),0.1,'zoh'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Simulate a data record
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
N       = 50*length(bq);
Z.u     = randn(1,N);
noise   = sqrt(var)*randn(size(Z.u));
Z.y     = filter(bq,1,Z.u)+noise;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Specify Model Structure
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
M.T     = T;
M.type  = 'fir';
M.nB    = length(bq)-1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Estimate on basis of noise corrupted data
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
G = est(Z,M,OPT);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Plot the results
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if dsp,
    Gt.B = bq(:)';
    Gt.type = 'fir';
    Gt.w = G.w;
    Gt.T = G.T;
    Gt.disp.colour='b';
    Gt.disp.legend = 'True Response';
    G.disp.legend = [G.disp.legend, ' q operator'];
    Gt.disp.aux='magonly';
    Gt = startM(Z,Gt);
    showbode(Gt,G);
end
echo off;
if dm
 disp('  ')
 disp('---------------------------------------------------------------------')
 disp('  ')
 disp('You now have access to the MATLAB workspace so that you may examine')
 disp('the results of this simulation.  To return to the demos, type "dbcont"')
 disp(' ')
 keyboard;
end;