Description of dzone
Home > unit > dzone.m
dzone
PURPOSE
Function to deadzone a signal u between a
SYNOPSIS
function z = dzone(u,lower,upper)
DESCRIPTION
  Function to deadzone a signal u between a
  lower and upper limit
  Usage is function z = dzone(u,lower,upper)
  Written by Brett Ninness: School of Elec. Eng. and Comp. Sci.
                            University of Newcastle
                            Australia
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demo_hammwiener Running this demos PEM estimatin of Hammerstein-Weiner Model Structure
demo_memoryless Running this demos estimation of a static (memoryless)
demo_miso_hammer Running this demos MISO Hammerstein system estimation
demo_miso_hammwiener Running this demos estimation of MISO Hammerstein-Wiener
demo_wiener Running this demos estimation of Weiner Model
details DETAILS: This function summarises details about a model structure.
u2x U2X - function to pass an input u through a specified non-linearity X so
SOURCE CODE
%  Function to deadzone a signal u between a
%  lower and upper limit
%
%  Usage is function z = dzone(u,lower,upper)
%
%  Written by Brett Ninness: School of Elec. Eng. and Comp. Sci.
%                            University of Newcastle
%                            Australia
% Copyright (C) Brett Ninness
function z = dzone(u,lower,upper)
[m,n]=size(u); u=u(:); z=zeros(size(u));
z(u<lower) = u(u<lower)-lower;
z(u>upper) = u(u>upper)-upper;
if n>m, z=z'; end