Description of finishM
Home > unit > finishM.m
finishM
PURPOSE
SYNOPSIS
function G = finishM(Z,M,OPT);
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
estmap This function provides a mapping from Model type (M.type) and Data type
m2f M2F - function to compute the frequency response of a linear time
m2sys M2SYS - function to convert an estimated model structure into Matlab
This function is called by:
SOURCE CODE
function G = finishM(Z,M,OPT);
G = M;  % Pass all input model structure information to output
% Get appropriate text description of model structure;
ep = estmap(Z,G,OPT); G.modelEquations = ep.modelEquations;
% Add a matlab-style system description
[G.sysG,G.sysH]=m2sys(G);
% Add a frequency response
G = m2f(G);
% Reorder fields in alphabetical order
G=orderfields(G);