Description of kronaw
Home > unit > kronaw.m
kronaw
PURPOSE
SYNOPSIS
function c = kronaw(a,b)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
fem This function tries to compute the maximum likelihood estimate of a
fsid FSID computes a state space model [A,B,C,D] that fits an observed (possibly
rksqrtv Square-root implementation of Kalman Filter/Smoother as per
systr SYSTR - function to simulate a bilinear system. Never meant to be
SOURCE CODE
function c = kronaw(a,b)
c = kron(a,b);