Description of rchol
Home > unit > rchol.m
rchol
PURPOSE
A function for computing the Cholesky factorisation,
SYNOPSIS
function [A] = rchol(A);
DESCRIPTION
 A function for computing the Cholesky factorisation,
                    A = X.'X,
 where X is a square, upper triangular matrix and A a square,
 symmetric (that is, A = A.') and positive semi-definite matrix.
 The usage is: X = rchol(A);
 Unlike many implementations of the Cholesky factorisation, this
 one copes with semi-definite A matrices (ones that have
 some zero eigenvalues).
   written by Brett Ninness, School of EE & CS
              Adrian Wills   University of Newcastle
                              Australia.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
em_sub EM_SUB: Subroutine called by EM.m that computes
fem This function tries to compute the maximum likelihood estimate of a
fsmooth /* Get sizes */
kfonestep
metropolis METROPOLIS: Metropolis algorithm implementation for generating a
rksqrtv Square-root implementation of Kalman Filter/Smoother as per
SOURCE CODE
% A function for computing the Cholesky factorisation,
%                    A = X.'X,
% where X is a square, upper triangular matrix and A a square,
% symmetric (that is, A = A.') and positive semi-definite matrix.
%
% The usage is: X = rchol(A);
%
% Unlike many implementations of the Cholesky factorisation, this
% one copes with semi-definite A matrices (ones that have
% some zero eigenvalues).
%
%   written by Brett Ninness, School of EE & CS
%              Adrian Wills   University of Newcastle
%                              Australia.
% Copyright (C) Brett Ninness
function [A] = rchol(A);
A = triu(A);
n = size(A,1);
tol=n*eps;
if A(1,1) <= tol,
 A(1,1:n) = 0;
else
 A(1,1:n) = A(1,1:n)/sqrt(A(1,1));
end
for j=2:n,
 A(j,j:n) = A(j,j:n) - A(1:j-1,j)'*A(1:j-1,j:n);
 if A(j,j) <= tol,
  A(j,j:n) = 0;
 else
  A(j,j:n) = A(j,j:n)/sqrt(A(j,j));
 end
end