Description of sat
Home > unit > sat.m
sat
PURPOSE
Function to saturate a signal u in the
SYNOPSIS
function z = sat(u,lower,upper,m)
DESCRIPTION
 Function to saturate a signal u in the
 interval [lower,upper] and with gain m.
  Usage is function z = sat(u,lower,upper,m)
  Written by Brett Ninness: School of Elec. Eng. and Comp. Sci.
                            University of Newcastle
                            Australia
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demo_hammer Running this demos PEM estimation of Hammerstein model structure
demo_hammwiener Running this demos PEM estimatin of Hammerstein-Weiner Model Structure
demo_memoryless Running this demos estimation of a static (memoryless)
demo_miso_hammer Running this demos MISO Hammerstein system estimation
demo_miso_hammwiener Running this demos estimation of MISO Hammerstein-Wiener
details DETAILS: This function summarises details about a model structure.
u2x U2X - function to pass an input u through a specified non-linearity X so
SOURCE CODE
function z = sat(u,lower,upper,m)
% Function to saturate a signal u in the
% interval [lower,upper] and with gain m.
%
%  Usage is function z = sat(u,lower,upper,m)
%
%
%  Written by Brett Ninness: School of Elec. Eng. and Comp. Sci.
%                            University of Newcastle
%                            Australia
% Copyright (C) Brett Ninness
if nargin<3 m=1; end;
if nargin<2 upper=-lower; end;
wun = ones(size(u));
z = max(min(m*u,upper*wun),lower*wun);