Description of subspace
Home > unit > subspace.m
subspace
PURPOSE
Function that calls underlying subspace algorithms depending on data
SYNOPSIS
function G = subspace(Z,M,OPT)
DESCRIPTION
  Function that calls underlying subspace algorithms depending on data
  type. E.g. equidistant discrete time data corresponds to the standard
  and well known N4SID or CCA algorithms. Likewise, frequency domain data
  will correspond to the frequency domain subspace algorithm.
   written by Brett Ninness, School of EE & CS
              Adrian Wills   University of Newcastle
                             Australia.
CROSS-REFERENCE INFORMATION
This function calls:
fsid FSID computes a state space model [A,B,C,D] that fits an observed (possibly
sid This function estimates a state-space model for a possibly
startZ This function accepts a data structure and tries to interpret what type
This function is called by:
est EST: Computes an estimate of either a Box-Jenkins model or a state space
startG STARTG - function to initialise estimate of dynamics model in case user
SOURCE CODE
%  Function that calls underlying subspace algorithms depending on data
%  type. E.g. equidistant discrete time data corresponds to the standard
%  and well known N4SID or CCA algorithms. Likewise, frequency domain data
%  will correspond to the frequency domain subspace algorithm.
%
%   written by Brett Ninness, School of EE & CS
%              Adrian Wills   University of Newcastle
%                             Australia.
%
% Copyright (C) Brett Ninness
function G = subspace(Z,M,OPT)
% Make sure Z has been parsed
Z=startZ(Z);
if nargin<2,
 M   = [];
 OPT = [];
elseif nargin<3,
 OPT = [];
end
% Now switch according to data type
switch Z.type
 case 'time'
  G = sid(Z,M,OPT);
 case 'frequency'
  G = fsid(Z,M,OPT);
 otherwise
  error('Data type (Z.type) not known');
end