Description of udisp
Home > unit > udisp.m
udisp
PURPOSE
SYNOPSIS
function udisp(str,guiRunning,guiHandle)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
argmin Function to find minimum of function that is defined by user supplied
em_sub EM_SUB: Subroutine called by EM.m that computes
est EST: Computes an estimate of either a Box-Jenkins model or a state space
fem This function tries to compute the maximum likelihood estimate of a
gn This function calls underlying gradient-based search algorithms, based on
startG STARTG - function to initialise estimate of dynamics model in case user
startH STARTH - function to initialise estimate of noise model in case user
SOURCE CODE
function udisp(str,guiRunning,guiHandle)
if guiRunning
 guiHandle.gui.eto.myEstModelPopup.append(str);
else
 disp(str);
end